In [14]:
import numpy as np
import time

# 计时器
class Timer():
    def __init__(self):
        self.start_time = None
        self.end_time = None

    def start(self):
        self.start_time = time.perf_counter()

    def stop(self):
        self.end_time = time.perf_counter()

    def elapsed(self):
        if self.start_time is not None and self.end_time is not None:
            return self.end_time - self.start_time
        else:
            return None

In [4]:
# NumPy 数组的基本属性

SampleNdarray = np.array([[1, 2, 3], [4, 5, 6]])
print(SampleNdarray)
print(SampleNdarray.shape)
print(SampleNdarray.dtype)
print(SampleNdarray.ndim)
print(SampleNdarray.size)
print(SampleNdarray.flags)
print(SampleNdarray.flat)
for item in SampleNdarray.flat:
    print(item)
print(SampleNdarray.itemsize)
print(SampleNdarray.strides)

# 与 Python 数据类型的区别
print(type(SampleNdarray[0, 0]))
print(type(0))

[[1 2 3]
 [4 5 6]]
(2, 3)
int32
2
6
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

1
2
3
4
5
6
4
(12, 4)
<class 'numpy.int32'>
<class 'int'>


In [ ]:
# 索引和切片
print("索引和切片")
print(SampleNdarray[0], "\n")
print(SampleNdarray[0, 0], "\n")
print(SampleNdarray[0, :], "\n")
print(SampleNdarray[:, 0], "\n")
print(SampleNdarray[0:2, 0:2], "\n")
print(SampleNdarray[:, 0::2], "\n")

# 高级索引
print("高级索引")
print(SampleNdarray[[0, 1], [1, 2]], "\n")
print()


索引和切片
[1 2 3] 

1 

[1 2 3] 

[1 4] 

[[1 2]
 [4 5]] 

[[1 3]
 [4 6]]
高级索引
[2 6] 



<function print>

In [9]:
a = np.array([[1, 2, 3],            
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

In [15]:
Timer = Timer()
Timer.start()
a.__add__(b)
Timer.stop()
print(Timer.elapsed())

print(a)
print(b)

Timer.start()
a + b
Timer.stop()
print(Timer.elapsed())

6.230000008144998e-05
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
8.100000013655517e-05


In [ ]:
Timer.start()
a.__add__(b)
Timer.stop()
print(Timer.elapsed())

Timer.start()
a + b
Timer.stop()
print(Timer.elapsed())

9.269999986827315e-05
5.989999999655993e-05
