In [1]:
import numpy as np

In [ ]:
# NumPy 数组的基本属性

SampleNdarray = np.array([[1, 2, 3], [4, 5, 6]])
print(SampleNdarray)
print(SampleNdarray.shape)
print(SampleNdarray.dtype)
print(SampleNdarray.ndim)
print(SampleNdarray.size)
print(SampleNdarray.flags)
print(SampleNdarray.itemsize)
print(SampleNdarray.strides)

# 与 Python 数据类型的区别
print(type(SampleNdarray[0, 0]))
print(type(0))

[[1 2 3]
 [4 5 6]]
(2, 3)
int32
2
6
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

4
(12, 4)
<class 'numpy.int32'>
<class 'int'>


In [ ]:
# 索引和切片
print("索引和切片")
print(SampleNdarray[0], "\n")
print(SampleNdarray[0, 0], "\n")
print(SampleNdarray[0, :], "\n")
print(SampleNdarray[:, 0], "\n")
print(SampleNdarray[0:2, 0:2], "\n")
print(SampleNdarray[:, 0::2], "\n")

# 高级索引
print("高级索引")
print(SampleNdarray[[0, 1], [1, 2]], "\n")
print()


索引和切片
[1 2 3] 

1 

[1 2 3] 

[1 4] 

[[1 2]
 [4 5]] 

[[1 3]
 [4 6]]
高级索引
[2 6] 



<function print>